name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive  # needed for angular-realworld-example-app

      - name: Setup Node.js  # not needed but better use a specific node version + enable npm caching
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'  # enable npm cache
          cache-dependency-path: './realworld/apps/documentation/package-lock.json'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build your site
        run: |
          cd realworld/apps/documentation
          npm install
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './realworld/apps/documentation/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
